# aof-only.conf

# 本机 6380 端口
port 6380
bind 0.0.0.0
protected-mode no

# AOF 输出目录和文件名
dir /data
appendfilename aof-only.aof 

# 开启 AOF 持久化并设置同步策略
appendonly yes
appendfsync everysec

# 关闭 RDB 持久化
save ""

# 设置自动重写阈值和重写最小增量
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb