# rdb-aof-hybrid.conf

# 本机 6380 端口
port 6380
bind 0.0.0.0
protected-mode no

# 输出目录和文件名
dir /data
dbfilename rdb-aof-hybrid.rdb
appendfilename rdb-aof-hybrid.aof

# 开启 RDB 和 AOF 持久化
appendonly yes
appendfsync everysec
save 5 10

# 快照失败后停止写入
stop-writes-on-bgsave-error yes

# 设置自动重写阈值和重写最小增量
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb