# rdb-only.conf

# 本机 6380 端口
port 6380
bind 127.0.0.1
protected-mode no

# 输出目录和文件名
dir /redis/data/rdb-only
dbfilename rdb-only.rdb

# 关闭 AOF 持久化
appendonly no

# 异步后台保存 5s内 10次写入 bgsave 一次
save 5 10 

# 快照失败后停止写入
stop-writes-on-bgsave-error yes